apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-test-test-test-test-test-test-test-tet
  namespace: test
spec:
    spec:
      containers:
        - name: test
          image: nahsilabs/test:0.8.146 # x-release-please-version
