apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-test-test-test-test-test-test
spec:
    spec:
      containers:
        - name: test
          image: nahsilabs/test:0.8.144 # x-release-please-version
